Environment:
	Python: 3.8.16
	PyTorch: 1.13.1+cu117
	Torchvision: 0.14.1+cu117
	CUDA: 11.7
	CUDNN: 8500
	NumPy: 1.23.5
	PIL: 9.3.0
Traceback (most recent call last):
  File "../train.py", line 107, in <module>
    train_loaders, eval_loaders = get_img_dataloader(args)
  File "/home/jiajunlong/Documents/domain/transferlearning/code/DeepDG/datautil/getdataloader.py", line 22, in get_img_dataloader
    tmpdatay = ImageDataset(args.dataset, args.task, args.data_dir,
  File "/home/jiajunlong/Documents/domain/transferlearning/code/DeepDG/datautil/imgdata/imgdataload.py", line 12, in __init__
    self.imgs = ImageFolder(root_dir+domain_name).imgs
  File "/home/jiajunlong/anaconda3/envs/DG/lib/python3.8/site-packages/torchvision/datasets/folder.py", line 309, in __init__
    super().__init__(
  File "/home/jiajunlong/anaconda3/envs/DG/lib/python3.8/site-packages/torchvision/datasets/folder.py", line 144, in __init__
    classes, class_to_idx = self.find_classes(self.root)
  File "/home/jiajunlong/anaconda3/envs/DG/lib/python3.8/site-packages/torchvision/datasets/folder.py", line 218, in find_classes
    return find_classes(directory)
  File "/home/jiajunlong/anaconda3/envs/DG/lib/python3.8/site-packages/torchvision/datasets/folder.py", line 40, in find_classes
    classes = sorted(entry.name for entry in os.scandir(directory) if entry.is_dir())
FileNotFoundError: [Errno 2] No such file or directory: '/home/jiajunlong/Documents/domain/transferlearning/code/DeepDGdata/PACS/art_painting'
